name: "Continuous Delivery"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.8.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials cluster-latam --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl config use-context gke_${{ secrets.GCP_PROJECT_ID }}_us-central1-a_cluster-latam

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
